export const AreadeAtuacaoAtendidas = [
  'Cirurgia do Joelho',
  'Cirurgia da Mão',
  'Ombro e Cotovelo',
  'Ortopedia Pediatrica',
  'Cirurgia do Ombro',
  'Cirurgia do pé e tornozelo',
  'Cirurgia do Quadril',
  'Cirurgia da Coluna',
  'Arritmias e Eletrofisiologia Cardíaca',
  'Ecocardiografia',
  'Transplantes',
  'Miocardiopatias',
  'Cardiologia Pediátrica',
  'Ergometria e reabilitação',
  'Hipertensão Arterial',
  'Hemodinâmica',
  'ginecologia endócrina', 
  'reprodução humana',
  'estática pélvica',
  'uroginecologia',
  'mastologia',
  'oncologia pélvica',
  'medicina fetal',
  'Psicogeriatria',
  'Psicoterapia',
  'Psiquiatria da Infância e Adolescência',
  'Psiquiatria Forense',
  'Sexologia',
  'Clinico Geral'
]
