export const diseases = [
  "Acidente Vascular Cerebral (AVC)",
  "Acne",
  "Afasia Primária",
  "Alcoolismo",
  "Alergia",
  "Alopecia",
  "Amamentação",
  "Aneurisma",
  "Aneurisma Cerebral",
  "Angina",
  "Anorexia",
  "Ansiedade",
  "Apneia do Sono",
  "Arritmia",
  "Arterites",
  "Artrite",
  "Artrite Psoriática",
  "Artrite Reumatóide",
  "Artrose",
  "Asma",
  "Ataxia",
  "Atrofia Muscular Espinhal (AME)",
  "Autismo",
  "Azia",
  "Baixa Libido",
  "Bechet",
  "Bipolar",
  "Bronquite",
  "Bruxismo",
  "Bulimia",
  "Burnout",
  "Bursite",
  "Cálculos Biliares",
  "Câncer de Bexiga",
  "Câncer de Boca",
  "Câncer de Cabeça e Pescoço",
  "Câncer de Colo de Útero",
  "Câncer de Cólon",
  "Câncer de Mama",
  "Câncer de Ovário",
  "Câncer de Pâncreas",
  "Câncer de Pele",
  "Câncer de Próstata",
  "Câncer de Pulmão",
  "Câncer de Tecidos Moles",
  "Câncer de Testículo",
  "Câncer de Tireoide",
  "Câncer de Vias Biliares",
  "Câncer Metastático",
  "Câncer no Cérebro",
  "Câncer no Esôfago",
  "Câncer no Estômago",
  "Câncer no Fígado",
  "Câncer no Intestino",
  "Câncer no Osso",
  "Câncer no Rim",
  "Candidíase",
  "Caquexia",
  "Carcinoma Basocelular",
  "Carcinoma de Pele",
  "Carcinoma Espinocelular",
  "Cardiopatia Congênita",
  "Carpo",
  "Cefaleia em Salvas",
  "Cefaleia Tensional",
  "Cervicalgia",
  "Cirrose Hepática",
  "Cistite",
  "Citomegalovírus",
  "Colesterol Alto",
  "Cólica",
  "Cólica Menstrual",
  "Colite",
  "Cólon irritável",
  "Compulsão Alimentar",
  "Conjunctivite",
  "Constipação Intestinal",
  "Contratura de Dupuytren",
  "Contratura Muscular",
  "Convulsões",
  "Coreia",
  "Corrimento Vaginal",
  "Covid-19",
  "Déficit de Atenção",
  "Degeneração Macular",
  "Demência de Alzheimer",
  "Demência Senil",
  "Dengue",
  "Dependência de Álcool",
  "Dependência de Benzodiazepínicos",
  "Dependência de Cocaína",
  "Dependência de Crack",
  "Dependência de Maconha",
  "Dependência de Nicotina",
  "Dependência Química",
  "Depressão",
  "Depressão com Risco Suicídio",
  "Dermatite",
  "Dermatite Alérgica",
  "Dermatite Atópica",
  "Dermatite de Contato",
  "Dermatomiosite",
  "Derrame",
  "Derrame Cerebral",
  "Diabetes",
  "Diarreia",
  "DIP",
  "Dislexia",
  "Distonia",
  "Distrofia Muscular",
  "Diverticulite",
  "Doença Autoimune",
  "Doença Celíaca",
  "Doença de Chagas",
  "Doença de Chron",
  "Doença de Huntington",
  "Doença de Machado-Joseph",
  "Doença de Parkinson",
  "Doença Inflamatória pélvica",
  "Dor Crônica",
  "Dor de Barriga",
  "Dor de Cabeça",
  "Dor na Coluna",
  "Dor no Ombro",
  "Dor no Pescoço",
  "Dor Muscular",
  "Dor na Cervical",
  "Dor na Lombar",
  "Dor na Mão",
  "Dor nas Costas",
  "Dor no Ato Sexual",
  "Dor no Braço",
  "Dor no Câncer",
  "Dor no Ciático",
  "Dor no Cóccix",
  "Dor no Joelho",
  "Dor no Pé",
  "Dor no Peito",
  "Dor no Quadril",
  "Dor no Tornozelo",
  "Doença Osteomuscular Relacionada ao Trabalho (DORT)",
  "Doença Pulmonar Obstrutiva Crônica (DPOC)",
  "Dupuytren",
  "Eczema",
  "Esclerose Lateral Amiotrófica (ELA)",
  "Embolia Pulmonar",
  "Encefalite",
  "Endometriose",
  "Enfisema Pulmonar",
  "Enxaqu
