export const DoençasAtendidas = [
    "Acidente Vascular Cerebral (AVC)",
    "Acne",
    "Afasia Primária",
    "Alcoolismo",
    "Alergia",
    "Alopecia",
    "Amamentação",
    "Aneurisma",
    "Aneurisma Cerebral",
    "Angina",
    "Anorexia",
    "Ansiedade",
    "Apneia do Sono",
    "Arritmia",
    "Arterites",
    "Artrite",
    "Artrite Psoriática",
    "Artrite Reumatóide",
    "Artrose",
    "Asma",
    "Ataxia",
    "Atrofia Muscular Espinhal (AME)",
    "Autismo",
    "Azia",
    "Baixa Libido",
    "Bechet",
    "Bipolar",
    "Bronquite",
    "Bruxismo",
    "Bulimia",
    "Burnout",
    "Bursite",
    "Cálculos Biliares",
    "Câncer de Bexiga",
    "Câncer de Boca",
    "Câncer de Cabeça e Pescoço",
    "Câncer de Colo de Útero",
    "Câncer de Cólon",
    "Câncer de Mama",
    "Câncer de Ovário",
    "Câncer de Pâncreas",
    "Câncer de Pele",
    "Câncer de Próstata",
    "Câncer de Pulmão",
    "Câncer de Tecidos Moles",
    "Câncer de Testículo",
    "Câncer de Tireoide",
    "Câncer de Vias Biliares",
    "Câncer Metastático",
    "Câncer no Cérebro",
    "Câncer no Esôfago",
    "Câncer no Estômago",
    "Câncer no Fígado",
    "Câncer no Intestino",
    "Câncer no Osso",
    "Câncer no Rim",
    "Candidíase",
    "Caquexia",
    "Carcinoma Basocelular",
    "Carcinoma de Pele",
    "Carcinoma Espinocelular",
    "Cardiopatia Congênita",
    "Carpo",
    "Cefaleia em Salvas",
    "Cefaleia Tensional",
    "Cervicalgia",
    "Cirrose Hepática",
    "Cistite",
    "Citomegalovírus",
    "Colesterol Alto",
    "Cólica",
    "Cólica Menstrual",
    "Colite",
    "Cólon irritável",
    "Compulsão Alimentar",
    "Conjuntivite",
    "Constipação Intestinal",
    "Contratura de Dupuytren",
    "Contratura Muscular",
    "Convulsões",
    "Coreia",
    "Corrimento Vaginal",
    "Covid-19",
    "Déficit de Atenção",
    "Degeneração Macular",
    "Demência de Alzheimer",
    "Demência Senil",
    "Dengue",
    "Dependência de Álcool",
    "Dependência de Benzodiazepínicos",
    "Dependência de Cocaína",
    "Dependência de Crack",
    "Dependência de Maconha",
    "Dependência de Nicotina",
    "Dependência Química",
    "Depressão",
    "Depressão com Risco Suicídio",
    "Dermatite",
    "Dermatite Alérgica",
    "Dermatite Atópica",
    "Dermatite de Contato",
    "Dermatomiosite",
    "Derrame",
    "Derrame Cerebral",
    "Diabetes",
    "Diarreia",
    "DIP",
    "Dislexia",
    "Distonia",
    "Distrofia Muscular",
    "Diverticulite",
    "Doença Autoimune",
    "Doença Celíaca",
    "Doença de Chagas",
    "Doença de Chron",
    "Doença de Huntington",
    "Doença de Machado-Joseph",
    "Doença de Parkinson",
    "Doença Inflamatória pélvica",
    "Dor Crônica",
    "Dor de Barriga",
    "Dor de Cabeça",
    "Dor na Coluna",
    "Dor no Ombro",
    "Dor no Pescoço",
    "Dor Muscular",
    "Dor na Cervical",
    "Dor na Lombar",
    "Dor na Mão",
    "Dor nas Costas",
    "Dor no Ato Sexual",
    "Dor no Braço",
    "Dor no Câncer",
    "Dor no Ciático",
    "Dor no Cóccix",
    "Dor no Joelho",
    "Dor no Pé",
    "Dor no Peito",
    "Dor no Quadril",
    "Dor no Tornozelo",
    "Doença Osteomuscular Relacionada ao Trabalho (DORT)",
    "Doença Pulmonar Obstrutiva Crônica (DPOC)",
    "Dupuytren",
    "Eczema",
    "Esclerose Lateral Amiotrófica (ELA)",
    "Embolia Pulmonar",
    "Encefalite",
    "Endometriose",
    "Enfisema Pulmonar",
    "Enxaqueca",
    "Epicondilite",
    "Epilepsia",
    "Escara",
    "Esclerodermia",
    "Esclerose Múltipla",
    "Espasmo Muscular",
    "Espinha",
    "Espondilite Anquilosante",
    "Espondiloartrite",
    "Esporão do Calcâneo",
    "Esquizofrenia",
    "Estenose de Canal",
    "Fadiga",
    "Fasciíte Plantar",
    "Febre Reumática",
    "Ferida Crônica",
    "Fibrilação Atrial",
    "Fibromialgia",
    "Fibrose Cística",
    "Fígado Gorduroso",
    "Fobia social",
    "Fogachos",
    "Fratura",
    "Fratura no Câncer",
    "Fratura Pós Trauma",
    "Galactorreia",
    "Ganho de Peso",
    "Gastrite",
    "Gestação",
    "Glaucoma",
    "Gonorreia",
    "Gota",
    "Gripe",
    "H. Pylori",
    "Hanseníase",
    "Hemorróidas",
    "Hepatite",
    "Hérnia de Disco",
    "Hérnia de Hiato",
    "Herpes",
    "Hidrocefalia",
    "Hipersonolência",
    "Hipertensão",
    "Hipertireoidismo",
    "Hipotireoidismo",
    "HIV / AIDS",
    "HPV",
    "Infarto",
    "Infecção de Pele",
    "Infecção no Intestino",
    "Infecção Urinária",
    "Influenza",
    "Insônia",
    "Insuficiência Cardíaca",
    "Intestino Irritável",
    "Intestino Preso",
    "Intolerância ao Glúten",
    "Lesão por Esforço Repetitivo (LER)",
    "Leucemia",
    "Linfoma",
    "Lombalgia",
    "Lúpus Eritematoso Sistêmico",
    "Mal de Parkinson",
    "Melanoma",
    "Meningite",
    "Menopausa",
    "Metástase",
    "Miastenia Gravis",
    "Micardite",
    "Micose",
    "Mielite",
    "Migrânea",
    "Mioma Uterino",
    "Miopatia",
    "Náuseas",
    "Neuralgia do Trigêmeo",
    "Neuralgia Pós-herpética",
    "Neuropatia Diabética",
    "Neuropatia Induzida por Drogas",
    "Nódulo Pulmão",
    "Obesidade",
    "Osteomielite",
    "Osteoporose",
    "Outras Demências",
    "Ovários Policísticos",
    "Pancreatite",
    "Paralisia Cerebral",
    "Paralisia de Bell",
    "Paralisia Facial",
    "Paralisia Supranuclear Progressiva",
    "Pedra na Vesícula",
    "Perda de Apetite",
    "Perda de Cabelo",
    "Perda de Peso",
    "Pneumonia",
    "Polimiosite",
    "Polineuropatia Diabética",
    "Polineuropatia Inflamatória",
    "Pólipo Intestinal",
    "Pressão Alta",
    "Prisão de Ventre",
    "Prostração",
    "Psoríase",
    "Queda de Cabelo",
    "Queda na Libido",
    "Queimação",
    "Rabdomiossarcoma",
    "Refluxo",
    "Reposição Hormonal",
    "Retinopatia Diabética",
    "Retocolite Ulcerativa",
    "Reumatismo",
    "Rinite",
    "Rubéola",
    "SAF",
    "Sequelas Pós-AVC",
    "Sequelas Pós-TCE",
    "Sequelas Pós-TRM",
    "Sífilis",
    "Síndrome Antifosfolípide",
    "Síndrome da Fadiga Crônica",
    "Síndrome das Pernas Inquietas",
    "Síndrome de Cushing",
    "Síndrome de Down",
    "Síndrome de Dravet",
    "Síndrome de Lennox-Gastaut",
    "Síndrome de Sjögren",
    "Síndrome de Tourette",
    "Síndrome do Intestino Irritável",
    "Síndrome do Pânico",
    "Síndrome Inflamatória Intestinal",
    "Síndrome Pós-Covid",
    "Síndrome seca",
    "Síndrome Túnel do Carpo",
    "Sinovite",
    "Sinusite",
    "Tabagismo",
    "Taquicardia",
    "Tendinite",
    "Tireoide",
    "Toxoplasmose",
    "Transtorno Bipolar Afetivo",
    "Transtorno de Déficit de Atenção e Hiperatividade (TDAH)",
    "Transtorno de Estresse Pós-Traumático (TEPT)",
    "Transtorno de Personalidade",
    "Transtorno do Espectro Autista (TEA)",
    "Transtorno do Plexo Braquial",
    "Transtorno Obsessivo Compulsivo (TOC)",
    "Transtornos do Sono",
    "Traumatismo Cranioencefálico",
    "Traumatismo Raquimedular",
    "Tremor Essencial",
    "Triglicerídeos Alto",
    "Tuberculose",
    "Túnel do Carpo",
    "Úlcera de Decúbito",
    "Úlcera Estômago",
    "Úlcera Péptica",
    "Úlcera Varicosa",
    "Vaginite",
    "Vaginose",
    "Varicela",
    "Vasculites",
    "Virose",
    "Vômitos",
    "Zika",
  ];
  