FROM node:latest

WORKDIR /front

COPY frontinterconsulta/ .

RUN apt-get update && \
    apt-get install -y git && \ 
    npm install

RUN npm install sharp

RUN npm run build 

EXPOSE 3000

CMD ["npm", "run", "start"]
