FROM node:latest

ENV PUPPETEER_SKIP_DOWNLOAD=true \
    TZ=America/Sao_Paulo

WORKDIR /app

RUN apt-get update && \
    apt-get install -y build-essential git libvips && \
    apt-get clean && \
    rm -rf /var/lib/apt/lists/*

COPY backinterconsulta/ApiFeatures .

RUN npm install

RUN rm -rf node_modules/bcrypt \
    && npm install bcrypt

EXPOSE 8
