FROM node:latest

WORKDIR /front

RUN ln -sf /usr/share/zoneinfo/America/Sao_Paulo /etc/localtime

COPY frontinterconsulta/ .

RUN apt-get update && \
    apt-get install -y git && \ 
    rm -rf node_modules && \
    npm install

RUN npm install sharp

RUN npm run build 

EXPOSE 3000

CMD ["npm", "run", "start"]
