# Use an official Node.js runtime as the base image
FROM node:16-alpine

# Set the working directory to /app
WORKDIR /app

# Copy the current directory contents into the container at /app
COPY . /app

# Install git and any needed dependencies
RUN apk add --no-cache git

# Install Node.js dependencies
RUN npm ci

# Build the application
RUN npm run build

# Expose port 3000 for the app
EXPOSE 3000

# Start the app
CMD ["npm", "run", "start"]
