version: '3.8'

services:

  redis:
    image: redis
    container_name: redisFila
    ports:
      - "6379:6379"
    networks:
      - net-interconsulta

  backfeatures:
    build:
      context: .
      dockerfile: Dockerfile.backFeatures
    container_name: backendF
    ports:
      - 8080:8080
    depends_on:
      - redis
    networks:
      - net-interconsulta
    volumes:
      - backfeatures-uploads:/app/uploads

  back-a:
    build:
      context: .
      dockerfile: Dockerfile.backAutomacoes
    container_name: backendA
    ports:
      - 8081:8081
    depends_on:
      - redis
      - backfeatures
    networks:
      - net-interconsulta

  frontend:
    build:
      context: .
      dockerfile: Dockerfile.front
    container_name: frontend-container
    ports:
      - 3000:3000
    depends_on:
      - backfeatures
      - back-a
    networks:
      - net-interconsulta

  nginx:
    build:
      context: .
      dockerfile: Dockerfile.reverseProxy
    container_name: nginx-container 
    restart: always
    ports:
      - "80:80"
    depends_on:
      - backfeatures
      - back-a
      - frontend
    networks:
      - net-interconsulta
    volumes:
      - ./certbot/conf:/etc/letsencrypt
      - ./certbot/www:/var/www/certbot

  certbot:
    image: certbot/certbot  
    container_name: certbot
    volumes: 
      - ./certbot/conf:/etc/letsencrypt
      - ./certbot/www:/var/www/certbot
    depends_on:
      - nginx
    networks:
      - net-interconsulta

volumes:
  backfeatures-uploads:

networks:
  net-interconsulta:
    driver: bridge
