FROM node:latest

WORKDIR /app

RUN apt-get update && \
    apt-get install -y build-essential && \
    apt-get clean && \
    rm -rf /var/lib/apt/lists/*
    
COPY backinterconsulta/ApiFeatures .

RUN rm -rf node_modules/bcrypt

# Instalando as dependências necessárias para o sharp
RUN npm install --ignore-scripts=false --verbose sharp

# Instalando o módulo bcrypt de novo
RUN npm install bcrypt

# Instalação das demais dependências do projeto
RUN npm install

CMD ["npm", "run", "dev"]
