import mongoose from 'mongoose'

const DadosIniciais = {
  nome: String,
  senha: String,
  email: String,
  telefone: String,
}

const ModelDataCasosClinicos = {
  Usuario: String,
  UnidadeSaude: String,
  AreadeAtuacao: String,
  Posição: String,
  MatrículaProntuário: String,
  CartãoSUS: String,
  Telefone: String,
  Email: String,
  Acompanhante: String,
  TelefoneAcompanhante: String,
  EmailAcompanhante: String,
  Endereço: String,
  Cidade: String,
  Estado: String,
  Pais: String,
  DataInsercao: String,
  Procedimento: String,
  CodProcedimento: String,
  CRM: String,
  Solicitante: String,
  Especialidade: String,
  SubEspecialidade: String,
  TipoSolicitaçao: String,
  Diagnóstico: String,
  Tratamento: String,
  Medicação: String,
  FerramentaTerapêutica: String,
  ProgressoPaciente: String,
  RecomendaçõesFuturas: String,
  StatusPaciente: String,
  Medicamentos: [String],
  Material: [String],
  Data: String,
  FotoEspecialidade: String,
  ResumoCasoClinico: String
}

const ModelGestoesSolicitadas = {
  AreadeAtuacao: String,
  Inicio: String,
  Fim: String,
  OrçamentoEscolhido: String,
  ValorPorConsulta: String,
  CréditosDisponiveis: String,
  DiferençaDiasGestor: String,
  QuantidadeCasosClinicosPlanilha: String,
  AtendimentoNecessariosDia: String,
  SaudoDisponivel: String,
  QuantidadeMedicosDisponiveis: String,
  DatasMedicosDisponiveis: [String],
  QuantidadeHorariosMedicosDisponiveis: String,
  AtendimentosDiaMedicos:[String],
  ValorTotalAtendimentosDiaMedico: String,
  AgendamentosFaltando: String,
  DiferencaEntreDiasDosMedicos: String,
  CasosClinicosSuportados: String,
  MediaAtendimentosDia: String,
  FraseFinalConsolidada: String,
  OrçamentoEstimado: String,
  MedicosDisponiveis: [{
     Nome: String,
     Especialidade: String,
     AreadeAtuacao: String,
     CRM: String,
  }]
}

const RegisterMédico = new mongoose.Schema({
  ...DadosIniciais,
  NomeEspecialista: String,
  NomeConhecido:String,
  TituloEspecialista: String,
  FormacaoEspecialista: String,
  PosGraduacao: String,
  EspecialidadeMedica: String,
  AreadeAtuacao: String,
  CRM: String,
  RQE: String,
  Certificacao: String,
  ResumoProfissional: String,
  Slug: String,
  Foto: String, 
  online: Boolean,
  FotoEspecialidade: String,
  PrecoConsulta: String,
  DataNascimento: String,
  Idade: String,
  FerramentasTerapeuticas: [String],
  AnoGraduacao: String,
  QuantidadeTempoAnoGraduacao: String,
  InstituicaoResidencia: String,
  NomeTitular: String,
  NumeroConta: String,
  NumeroAgencia: String,
  Banco: String,
  ChavePix: String,
  CPNJMedico: String,
  RazaoSocialEmpresa: String,
  NomeFantasia: String,
  EnderecoMedico: String,
  Bairro: String,
  Cidade: String,
  Estado: String,
  CEPMedico: String,
  EmailContador: String,
  TelefoneContador:String,
  DoencasAndSintomas: [{
    Doenca: String,
    Sintomas: [String],
    PrincipaisCausas: String,
    FormasDeTratamento: String,
    ComoPrevenir: String,
    TemCura:String,

  }],
  Horarios: [{
    data: String,
    inicio: String,
    fim: String,
    HorasDedicadas: Number,
    AtendimentosDia: Number,
    IntervaloAtendimentos: [{
      Intervalo: String,
      Escolhido: String,
      FotoPaciente: String,
    }],
    Gerado: String,
    DayDuplicate: Boolean,
    TempoDeConsulta: Number
  }],
  TotalAtendimentos:String,
  ConsultasSolicitadasPacientes: [{
    Data: String,
    Inicio: String,
    Fim: String,
    Solicitante: String,
    Solicitado: String,
    CPFPaciente: String,
    FotoPaciente: String,
    Casos: String,
    Status: String,
    HorarioSelecionado: String,
    Resumo: String,
    idHorario: String,
    TempoConsulta: Number,
    LinkConsulta: [{
      Link: String,
      expiration: Date,
    }],
    OkMedico: [String],
    OkPaciente: [String],
    PDF: Buffer,
  }],
  ConsultasUnidadedeSaude: [{
    Data: String,
    Inicio: String,
    Fim: String,
    Solicitante: String,
    Solicitado: String,
    Casos: [{
      CPF: String,
      Doenca: String,
      NomePaciente:String,
      QuantidadeCasosClinicos: Number,
      IdentificadorConsulta: String,
    }],
    CPF: String,
    Status: String,
    Consulta: String,
  }],
  Avaliacoes:[{
    AvaliacoesStar: Number,
    AvaliacoesText: String,
    Foto: String,
    NomePaciente: String,
  }],
  mediaAvaliacoes : Number,
  SafeID:[{
    authAPI: [{
      link: String,
      code: String,
      token: String,
      idSignature: String,
    }],
  }]
})

const RegisterPaciente = new mongoose.Schema({
  ...DadosIniciais,
  Genero: String,
  Data: String,
  Doenca: String,
  CPF: String,
  Foto: String,
  EspecialidadePaciente: String,
  Idade: String,
  TipoSanguineo: String,
  EstadoCivil: String,
  Profissao: String,
  CEP: String,
  EnderecoPaciente: String,
  CidadePaciente: String,
  EstadoPaciente: String,
  Pais: String,
  CartaoSUS: String,
  NomeAcompanhante: String,
  TelefoneAcompanhante: String,
  EmailAcompanhante: String,
  GifDoenca: String,
  QueixaInicial: String,
  ChavePix: String,
  ConsultasSolicitadasPacientes: [{
    Data: String,
    Inicio: String,
    Fim: String,
    Solicitante: String,
    Solicitado: String,
    CPFPaciente: String,
    Casos: String,
    Status: String,
    HorarioSelecionado: String,
    Resumo: String,
    idHorario: String,
    TempoConsulta: Number,
    LinkConsulta: [{
      Link: String,
      expiration: Date,
    }],
    OkMedico: [String],
    OkPaciente: [String],
  }],
  Historico:[{
    Diagnostico: String,
    Tratamento: String,
    Medicacao: String,
    FerramentasTerapeuticas: String,
    Progresso: String,
    SolicitacaoMedicamentos: String,
    SolicitacaoMateriais: String,
    SolicitacaoExames: String,
    RecomendacoesFuturas: String,
    EstadoPaciente: String,
    Solicitacao: String,
    CRMMedicoAtendeu:  String,
    DataInsercao: String,
    AreaAtuacao: String,
    Especialidade: String,
    ResumoCasoClinico: String,
  }],
})

const RegisterUnidadeSaude = new mongoose.Schema({
  ...DadosIniciais,
  Endereco: String,
  nomeInstituicao: String,
  CPNJ: String,
  EspecialidadeDesejada: String,
  Foto: String,
  GestoesSolicitadas: [{
    ...ModelGestoesSolicitadas  
  }],
  ConsultasUnidadedeSaude: [{
    Data: String,
    Inicio: String,
    Fim: String,
    Solicitante: String,
    Solicitado: String,
    Casos: [{
      CPF: String,
      Doenca: String,
      NomePaciente:String,  
      QuantidadeCasosClinicos: Number,
      IdentificadorConsulta: String,
    }],
    Status: String,
  }],
  ConsultasAceitasUnidade: [{
    grupos: [{
      Inicio: String,
      Fim: String,
      Status: String,
      Responsavel: String,
      CRMMedico: String,
      NomeMedico: String,
      NomePaciente: String,
      CPFPaciente: String,
      LinkConsulta: String
    }],
  }],
})

const CasosClinicos = new mongoose.Schema({
  NomePaciente:String,
  DataNascimento:String,
  Idade: String,
  Sexo: String,
  EstadoCivil:String,
  Profissão: String,
  CPF: String,
  TipoSanguineo: String,
    Historico:[{
      ...ModelDataCasosClinicos
    }],
  Duplicate: String,
})

const ListDoencasAndSintomasDoctor = new mongoose.Schema({
  Especialidade: String,
  AreadeAtuacao: String,
  DoencasESintomas:[{
    Doenca: String,
    Sintomas: [String],
    PrincipaisCausas: String,
    FormasDeTratamento: String,
    ComoPrevenir: String,
    TemCura:String,
  }]
})


const ModelRegisterMédico = mongoose.model('registerMédico', RegisterMédico)
const ModelRegisterPaciente = mongoose.model('registerPaciente', RegisterPaciente)
const ModelRegisterUnidadeSaude = mongoose.model('RegisterUnidadeSaude', RegisterUnidadeSaude)
const ModelCasosClinicos = mongoose.model('casosClinicos', CasosClinicos)
const List = mongoose.model('listDoctors', ListDoencasAndSintomasDoctor)

export const models = {
  ModelRegisterMédico,
  ModelRegisterPaciente,
  ModelRegisterUnidadeSaude,
  ModelCasosClinicos,
  List,
  SafeID,
};
