export const EspecialidadesAtendidas = [
  'Acupunturista',
  'Alergologista',
  'Anestesiologista',
  'Angiologista',
  'Cardiologia',
  'Cirurgião Cardiovascular',
  'Cirurgião da Mão',
  'Cirurgião de Cabeça e Pescoço',
  'Cirurgião do Aparelho Digestivo',
  'Cirurgião Geral',
  'Cirurgião Oncológico',
  'Cirurgião Pediátrico',
  'Cirurgião Plástico',
  'Cirurgião Torácico',
  'Cirurgião Vascular',
  'Clínico Geral',
  'Coloproctologista',
  'Dermatologista',
  'Endocrinologista',
  'Endoscopista',
  'Gastroenterologista',
  'Geneticista Médico',
  'Geriatra',
  'Ginecologia',
  'Hematologista',
  'Homeopata',
  'Infectologista',
  'Mastologista',
  'Médico de Emergência',
  'Médico de Família e Comunidade',
  'Médico do Trabalho',
  'Médico de Tráfego',
  'Médico Esportivo',
  'Médico Fisiatra',
  'Médico Intensivista',
  'Médico Legista',
  'Médico Nuclearista',
  'Médico de Medicina Preventiva',
  'Nefrologista',
  'Neurocirurgia',
  'Neurologista',
  'Nutrólogo',
  'Oftalmologista',
  'Oncologista Clínico',
  'Otorrinolaringologista',
  'Patologista',
  'Patologista Clínico',
  'Pediatra',
  'Pneumologista',
  'Psiquiatria',
  'Radiologista',
  'Radioterapeuta',
  'Reumatologista',
  'Urologista',
  'Ortopedista e Traumatologista'
];
