import { useState, useEffect } from 'react';
import Image from 'next/image';
import { EventAvailableIcon, EventBusyIcon, EventNoteIcon, DateRangeIcon, GroupsIcon } from '@mui/icons-material';
import secureLocalStorage from 'react-secure-storage';
import { useQuery, useMutation, useQueryClient } from '@tanstack/react-query';
import axios from 'axios';
import NotPaciente from '../partials/NotPaciente';
import PopUpUnidade from './AgendaUnidade';
import CasosClinico from '../partials/popUpCasoClinico';
import Checkbox from '@mui/material/Checkbox';
import CloseIcon from '@mui/icons-material/Close';
import StartIcon from '@mui/icons-material/Start';
import FingerprintIcon from '@mui/icons-material/Fingerprint';
import { useRouter } from 'next/navigation';
import Link from 'next/link';
import PopUpAviso from '../partials/popUpAviso';
import NotDateConsulta from '../partials/NotConsulta';
import PictureAsPdfIcon from '@mui/icons-material/PictureAsPdf';
import { saveAs } from 'file-saver';
import { config } from '../config.js';
import { useHorariosDoctor } from '../context/context';
import PopUpMedicoHoras from '../partials/PopUpHorasMedico';
import { useBlood } from "../context/context.js";
import Box from '@mui/material/Box';
import Tab from '@mui/material/Tab';
import TabContext from '@mui/lab/TabContext';
import TabList from '@mui/lab/TabList';
import TabPanel from '@mui/lab/TabPanel';
import PatientsDoctor from './PatientsDoctor';
import PopupCancelPaciente from '../partials/PopUpCancelPaciente';

export const MainAgenda = () => {
  const [keyConsulta, setKeyConsulta] = useState('');
  const [okMedico, setOkMedico] = useState(false);
  const [okPaciente, setOkPaciente] = useState(false);
  const [okUnidade, setOkUnidade] = useState(false);
  const [nomeMedico, setNomeMedico] = useState(null);
  const [idCasoPaciente, setidCasoPaciente] = useState([]);
  const [idCasoPaciente2, setidCasoPaciente2] = useState([]);
  const [CPFPaciente, setCPFPaciente] = useState([]);
  const [CPFPaciente2, setCPFPaciente2] = useState([]);
  const [NomePacientePublico, setNomePacientePublico] = useState([]);
  const [Solicitante, setSolicitante] = useState([]);
  const [Data, setData] = useState([]);
  const [Inicio, setInicio] = useState([]);
  const [Fim, setFim] = useState([]);
  const [StatusPaciente, setStatusPaciente] = useState(null);
  const [StatusMedico, setStatusMedico] = useState(null);
  const [StatusUnidade, setStatusUnidade] = useState(null);
  const [idCasoUnidade, setIdCasoUnidade] = useState([]);
  const [idCasoUnidade2, setIdCasoUnidade2] = useState([]);
  const [casoClinicoClicked, setCasoClinicoClicked] = useState([]);
  const [idMedico, setIDMedico] = useState('');
  const [doctorUnidade, setDoctorUnidade] = useState(null);

  const [
